### ISSUE TITLE
Missing language support

### ISSUE THREAD

**Issue by tux2603** [mlvzk/enterprise-hello-world#1]
Hello! This is a wonderful application, and I feel the ease of use is really beneficial to the user experience. However, I can't help but notice that Latin isn't supported. Did you not consider time traveling Romans as a potential user-base, or was this perhaps just an oversight.

Thanks

**Comment by mlvzk** [comment]
Hello. One of the major features of this application is that it follows the Suckless philosophy, this means if there is a feature a user needs they can add it themselves. I hope this helps!

**Comment by mlvzk** [comment]
(If you're representing a company we can also arrange our developers to merge the feature into upstream, given a good incentive ;))
